<?php

use Drupal\file\Entity\File;
use Drupal\thron\THRONApi;

/**
 * @file
 * Install, uninstall and update hooks for THRON module.
 */

/**
 * Implements hook_uninstall().
 */
function thron_uninstall() {
  // Clear variables.
  \Drupal::state()->delete(THRONApi::THRON_LAST_UPDATE_STATE_KEY);
  // Delete Medias.
  $media_storage = \Drupal::entityTypeManager()->getStorage('media');
  $thron_medias = $media_storage->getQuery()
    ->condition('bundle', 'thron_with_media_source')
    ->execute();

  if (!empty($thron_medias)) {
    $thron_medias = $media_storage->loadMultiple($thron_medias);
    try {
      $media_storage->delete($thron_medias);
    } catch (\Drupal\Core\Entity\EntityStorageException $e) {
      \Drupal::logger('thron')->error($e->getMessage());
    }
  }
}
